### ISSUE TITLE
What do you all think about my new repo?

### ISSUE THREAD

**Issue by jrandym** [jrandym/LinkedIn-Planning#4]
### Discussed in https://github.com/jrandym/LinkedIn-Planning/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **jrandym** June 30, 2024</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by RandyCHS** [comment]
I ❤️ it!

**Comment by jrandym** [comment]
Reviewed, closing issue
